<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * archiverRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class archiverRepository extends \Doctrine\ORM\EntityRepository
{
    public function archiver($now)
    {
        /*  $now = new \DateTime('now');
          $diff = $now->diff($blabla);
          $d1 = new DateTime('2009-e06-08 20:30:00');
          $d2 = new DateTime('2009-06-10 20:30:00');
          $diff = $d1->diff($d2);
            $nb_jours = $diff->d;
*/

        $qb = $this->getEntityManager()->createQueryBuilder();
        $c = $qb->select('c')
        ->from('KEURGUIimmoBundle:archiver', 'c')
        ->where('c.date->diff(:now)->d>7')
        ->setParameters(array(
            ':now' => $now,
            ))->getQuery();

        return $c->getResult();
    }
}
