<?php

namespace KEURGUI\immoBundle\Repository;

/**
 * archiveRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class archiveRepository extends \Doctrine\ORM\EntityRepository
{
    public function autoArchive($now)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $c = $qb->select('c')
        ->from('KEURGUIimmoBundle:archive', 'c')
        ->where(' DATE_DIFF(:now,c.date) >:sept')
        ->setParameters(array(
            ':now' => $now,
            ':sept' => 7,
            ))->getQuery();

        return $c->getResult();
    }

    public function autoSupprime($now)
    {
        $qb = $this->getEntityManager()->createQueryBuilder();
        $c = $qb->select('c')
        ->from('KEURGUIimmoBundle:archive', 'c')
        ->where(' DATE_DIFF(:now,c.date) >:quatorze')
        ->andWhere('c.archiv3=:a')
        ->setParameters(array(
            ':now' => $now,
            ':quatorze' => 14,
            ':a' => 1,
            ))->getQuery();

        return $c->getResult();
    }
}
